# Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
# Use either `docker-compose` or individual `docker build` commands
# Build
script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy

  # Tagging
  - docker tag udagram-api-feed thanhta97/udagram-api-feed:latest
  - docker tag udagram-api-user thanhta97/udagram-api-user:latest
  - docker tag udagram-frontend thanhta97/udagram-frontend:latest
  - docker tag udagram-reverseproxy thanhta97/udagram-reverseproxy:latest

# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push thanhta97/udagram-api-feed
  - docker push thanhta97/udagram-api-user
  - docker push thanhta97/udagram-frontend
  - docker push thanhta97/udagram-reverseproxy
