apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  credentials: FwoGZXIvYXdzEBgaDFoROPF55lZBJ/3ViyLVAZ8ZaaWaRLBPRzYdX9AyRIUaNy3KpSMWIQskKMSbJmRLU7Auy5ftjj6nY1Au0Iyu+YUx7+3m1x982Wbc5chKDFaJGYc29tQnHpGMqrbFSbstuFKmWqBcv6S6krC+NjzhhzIQwY4yJTZK4W4IpOvhvexweekVHhTbkHRBLWarYjwIreYWpSFc+GrMG4lbcroQbnbRx/4ngvAP8cyQxVwShn9NXNCXdo3RSY3lxHUj9ZhAhwidwH6xxmBioka5+pJpUZKPqz3FHi9AuuOSXXv5BYVRw1kC0CjEgrOdBjItuzi7MI0prgqajrsDZzBMw1ZD0yyPwdf4i4mcMsHtHKiTvlN4jgo8vUrvJ4IA