apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  credentials: FwoGZXIvYXdzEDwaDLai5LoDOwbPD3abdSLVAZusbv3zsoj8C1p306cf9mDMKqEQqtoqVgFCJSuyKkLgnkzUQ/YdtdStXFNmtq+sM2fwRayvrUXa4fW6W8NWha+Xw1QPOoG+nWWCwws1YI+S+M7IeUXYnxhniXVK0nlZ8bOmLLDZX2keFHQw91Lv1OLF9h2gA+3nZdfpyIiNBo5NULQbsHrMUKwCw6E1J9uQeTnOuo8v/wU0Q5nOATeNyjLzWcCbSn6gdBgPMYJv6I6eTOJ5Z8Ob1amsNioD6eqdamZv2Z2ZzpuZCKGrLpYhYLQkxz3Rsiij+7qdBjItXf69uonnaJ2KlnReiTohzPneS1lHGgXxG7xWmTdWARKSNP8I1EnP7ZQs/gCN