apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  credentials: FwoGZXIvYXdzEDMaDJQpPSxwIG2wTbLTdiLVAfkm9gUPJsLj6PeSGrgEWpOwbQl0eNb77ZcQmSbN620chCZAewFX2ZDQJmpXjNKXfRL0b7VG9TGQAV05EUSDmzAibKaxyaZ2YySVtQip3spNlTzWtCT/gBubnRl+4kR8axEt+r6qk+7RpFJpaH9MuoY60KsHXQ6mOBFiCcKQ62a0ub4Z1WjAvLIEwNnxMTgj3SoHls1S+L3EZpZu2nPXoTVYwbN+o9vk1yxQk6JQpzZN1HtU/Efp5IJ2jnwniWasVE5gKcDioRcCRkCUpWUxRf6i/D8jkCi+hbmdBjItssmZWiqMteeSiLvA6X9e9RN8Ovcdc1GRg/SWTGDqr7IXLNjFYyACKOo8OZE5